- name: SSD Wearout Report to Discord
  hosts: all
  gather_facts: false
  become: true

  vars:
    sata_device: /dev/sdh
    nvme_devices:
      - nvme0n1
      - nvme1n1
      - nvme2n1

  environment:
    PYTHONWARNINGS: "ignore"

  tasks:
    - name: Check SATA device exists
      stat:
        path: "{{ sata_device }}"
      register: sata_stat

    - name: Get SATA SSD info
      when: sata_stat.stat.exists
      block:
        - name: Read SATA SSD info
          shell: |
            smartctl -i {{ sata_device }}
          register: sata_info
          changed_when: false

        - name: Read SATA wearout
          shell: |
            smartctl -A {{ sata_device }} | awk '/Media_Wearout_Indicator/ {print $4}'
          register: sata_wear
          changed_when: false

        - name: Send SATA report to Discord
          ansible.builtin.uri:
            url: "{{ lookup('env', 'DISCORD_WEBHOOK_URL') }}"
            method: POST
            headers:
              Content-Type: application/json
            body_format: json
            body:
              content: >-
                The wearout percentage of
                **{{ sata_info.stdout | regex_search('Device Model:\\s*(.*)', '\\1') | default('Unknown') }}**.
                Serial:
                **{{ sata_info.stdout | regex_search('Serial Number:\\s*(.*)', '\\1') | default('Unknown') }}**.
                Wearout Remaining:
                **{{ sata_wear.stdout | default('Unavailable') }}%**.
            status_code: 204

    - name: Send SATA not found message
      when: not sata_stat.stat.exists
      ansible.builtin.uri:
        url: "{{ lookup('env', 'DISCORD_WEBHOOK_URL') }}"
        method: POST
        headers:
          Content-Type: application/json
        body_format: json
        body:
          content: "Device {{ sata_device }} not found."
        status_code: 204

    - name: Check NVMe devices
      loop: "{{ nvme_devices }}"
      loop_control:
        loop_var: nvme
      block:
        - name: Check NVMe exists
          stat:
            path: "/dev/{{ nvme }}"
          register: nvme_stat

        - name: Read NVMe info
          when: nvme_stat.stat.exists
          shell: |
            smartctl -i /dev/{{ nvme }}
          register: nvme_info
          changed_when: false

        - name: Read NVMe wear data
          when: nvme_stat.stat.exists
          shell: |
            smartctl -a /dev/{{ nvme }} | awk '/Percentage Used:/ {print $3}' | tr -d '%'
          register: nvme_used
          changed_when: false

        - name: Send NVMe report to Discord
          when: nvme_stat.stat.exists
          ansible.builtin.uri:
            url: "{{ lookup('env', 'DISCORD_WEBHOOK_URL') }}"
            method: POST
            headers:
              Content-Type: application/json
            body_format: json
            body:
              content: >-
                The wearout percentage of
                **{{ nvme_info.stdout | regex_search('Model Number:\\s*(.*)', '\\1') | default('Unknown') }}**.
                Serial:
                **{{ nvme_info.stdout | regex_search('Serial Number:\\s*(.*)', '\\1') | default('Unknown') }}**.
                Wearout Remaining:
                **{{ 100 - (nvme_used.stdout | int) }}%**.
            status_code: 204

        - name: Send NVMe not found message
          when: not nvme_stat.stat.exists
          ansible.builtin.uri:
            url: "{{ lookup('env', 'DISCORD_WEBHOOK_URL') }}"
            method: POST
            headers:
              Content-Type: application/json
            body_format: json
            body:
              content: "Device /dev/{{ nvme }} not found."
            status_code: 204
