---
- name: Collect disk usage and hostname
  hosts: all
  gather_facts: false
  become: false

  tasks:
    - name: Get hostname
      ansible.builtin.command: hostname
      register: hostname_out
      changed_when: false

    - name: Get root disk usage percentage
      ansible.builtin.shell: |
        df -h / | awk 'NR==2 {gsub("%",""); print $5}'
      register: disk_usage
      changed_when: false

    - name: Save host facts
      ansible.builtin.set_fact:
        host_name: "{{ hostname_out.stdout }}"
        root_disk_usage: "{{ disk_usage.stdout | int }}"

- name: Send aggregated disk report to Discord (Embed)
  hosts: localhost
  gather_facts: false

  vars:
    discord_webhook_url: "{{ lookup('env', 'DISCORD_WEBHOOK_URL') }}"
    disk_threshold: 80

  environment:
    PYTHONWARNINGS: "ignore"

  tasks:
    - name: Fail if DISCORD_WEBHOOK_URL is not set
      ansible.builtin.fail:
        msg: "DISCORD_WEBHOOK_URL environment variable is not set"
      when: discord_webhook_url is not defined or discord_webhook_url | length == 0

    - name: Build embed fields
      ansible.builtin.set_fact:
        embed_fields: |
          [
          {% for host in groups['all'] %}
            {% set usage = hostvars[host].root_disk_usage | default(-1) %}
            {% set name = hostvars[host].host_name | default(host) %}
            {
              "name": "{{ name }} ({{ host }})",
              "value": "{% if usage >= disk_threshold %}🔴 HIGH{% else %}🟢 OK{% endif %} — {{ usage }}%",
              "inline": false
            }{% if not loop.last %},{% endif %}
          {% endfor %}
          ]

    - name: Send embed report to Discord
      ansible.builtin.uri:
        url: "{{ discord_webhook_url }}"
        method: POST
        headers:
          Content-Type: application/json
        body_format: json
        body:
          embeds:
            - title: "📊 Disk Usage Summary (/)"
              color: 15158332   # red
              fields: "{{ embed_fields | from_yaml }}"
        status_code: 204
