- name: Send aggregated disk report to Discord (Table-style Embed)
  hosts: localhost
  gather_facts: false

  vars:
    discord_webhook_url: "{{ lookup('env', 'DISCORD_WEBHOOK_URL') }}"
    disk_threshold: 80

  environment:
    PYTHONWARNINGS: "ignore"

  tasks:
    - name: Build table columns
      set_fact:
        col_hostname: |
          {% for h in groups['all'] %}
          {{ hostvars[h].host_name | default(h) }}
          {% endfor %}
        col_ip: |
          {% for h in groups['all'] %}
          {{ h }}
          {% endfor %}
        col_disk: |
          {% for h in groups['all'] %}
          {{ hostvars[h].root_disk_usage }}%
          {% endfor %}
        col_status: |
          {% for h in groups['all'] %}
          {% if hostvars[h].root_disk_usage >= disk_threshold %}🔴 HIGH{% else %}🟢 OK{% endif %}
          {% endfor %}

    - name: Send table-style embed
      ansible.builtin.uri:
        url: "{{ discord_webhook_url }}"
        method: POST
        headers:
          Content-Type: application/json
        body_format: json
        body:
          embeds:
            - title: "📊 Disk Usage Summary (/)"
              color: 15158332
              fields:
                - name: "Hostname"
                  value: "{{ col_hostname }}"
                  inline: true
                - name: "IP"
                  value: "{{ col_ip }}"
                  inline: true
                - name: "Disk %"
                  value: "{{ col_disk }}"
                  inline: true
                - name: "Status"
                  value: "{{ col_status }}"
                  inline: true
        status_code: 204
