- name: Disk usage alert to Discord
  hosts: localhost
  gather_facts: false

  vars:
    discord_webhook_url: "{{ lookup('env', 'DISCORD_WEBHOOK_URL') }}"
    disk_threshold: 80

  environment:
    PYTHONWARNINGS: "ignore"

  tasks:
    - name: Build list of hosts over threshold
      set_fact:
        high_disk_hosts: >-
          {{
            groups['all']
            | selectattr('root_disk_usage', 'defined')
            | select(lambda h: hostvars[h].root_disk_usage | int >= disk_threshold)
            | list
          }}

    - name: Build alert message for high disk usage
      set_fact:
        alert_message: |
          🚨 **Disk Usage Alert (>= {{ disk_threshold }}%)**
          {% for h in high_disk_hosts %}
          • **{{ hostvars[h].host_name | default(h) }}**
            IP: {{ h }}
            Disk: {{ hostvars[h].root_disk_usage }}%
          {% endfor %}

    - name: Send "no issue" message if all hosts are OK
      ansible.builtin.uri:
        url: "{{ discord_webhook_url }}"
        method: POST
        headers:
          Content-Type: application/json
        body_format: json
        body:
          content: "✅ All hosts are below {{ disk_threshold }}% disk usage. No action required."
        status_code: 204
      when: high_disk_hosts | length == 0

    - name: Send alert message if there are hosts over threshold
      ansible.builtin.uri:
        url: "{{ discord_webhook_url }}"
        method: POST
        headers:
          Content-Type: application/json
        body_format: json
        body:
          content: "{{ alert_message }}"
        status_code: 204
      when: high_disk_hosts | length > 0
